# Generated by Django 4.0.1 on 2022-02-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0020_remove_ad_clicks_remove_ad_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
