# Generated by Django 4.0.1 on 2022-02-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0021_ad_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='view',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.view'),
            preserve_default=False,
        ),
    ]
