# Generated by Django 4.0.1 on 2022-02-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0022_click_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='view',
        ),
    ]
