# Generated by Django 4.0.1 on 2022-02-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0024_advertiser_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='author',
        ),
    ]
